# Generated by Django 4.0.7 on 2022-10-18 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eveonline', '0017_alliance_and_corp_names_are_not_unique'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('authentication', '0020_userprofile_language_userprofile_night_mode'),
        ('aadiscordmultiverse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discordmanagedserver',
            name='alliance_access',
            field=models.ManyToManyField(
                blank=True, help_text='Alliances to whose members this server is available.', to='eveonline.eveallianceinfo'),
        ),
        migrations.AddField(
            model_name='discordmanagedserver',
            name='character_access',
            field=models.ManyToManyField(
                blank=True, help_text='Characters to which this server is available.', to='eveonline.evecharacter'),
        ),
        migrations.AddField(
            model_name='discordmanagedserver',
            name='corporation_access',
            field=models.ManyToManyField(
                blank=True, help_text='Corporations to whose members this server is available.', to='eveonline.evecorporationinfo'),
        ),
        migrations.AddField(
            model_name='discordmanagedserver',
            name='faction_access',
            field=models.ManyToManyField(
                blank=True, help_text='Factions to whose members this server is available.', to='eveonline.evefactioninfo'),
        ),
        migrations.AddField(
            model_name='discordmanagedserver',
            name='group_access',
            field=models.ManyToManyField(
                blank=True, help_text='Groups to whose members this server is available.', to='auth.group'),
        ),
        migrations.AddField(
            model_name='discordmanagedserver',
            name='state_access',
            field=models.ManyToManyField(
                blank=True, help_text='States to whose members this server is available.', to='authentication.state'),
        ),
    ]
