# Generated by Django 4.0.7 on 2022-10-19 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aadiscordmultiverse', '0002_discordmanagedserver_alliance_access_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discordmanagedserver',
            options={'permissions': (('access_discord_multiverse', 'Can access the Discord Multiverse services'), (
                'access_all_discords', 'Can access the All the Discord Multiverse servers'))},
        ),
    ]
