# Generated by Django 4.0.8 on 2023-02-04 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('aadiscordmultiverse', '0003_alter_discordmanagedserver_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='discordmanagedserver',
            name='ignored_groups',
            field=models.ManyToManyField(
                blank=True, help_text='Groups that will not be synced to this discord server.', related_name='dmv_ignored_groups', to='auth.group'),
        ),
    ]
