# Generated by Django 4.2.13 on 2024-08-20 13:11

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('aadiscordmultiverse', '0004_discordmanagedserver_ignored_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='discordmanagedserver',
            name='include_all_managed_groups',
            field=models.BooleanField(default=True, help_text='Always sync Groups that are managed by Alliance Auth Core (corp/alliance)'),
        ),
        migrations.AddField(
            model_name='discordmanagedserver',
            name='included_groups',
            field=models.ManyToManyField(blank=True, help_text='Groups that will be synced to this discord server.', related_name='dmv_included_groups', to='auth.group'),
        ),
    ]
