# Generated by Django 4.2.13 on 2024-08-20 13:11

from django.db import migrations


def sync_groups_fwd(apps, schema_editor):
    DiscordManagedServer = apps.get_model('aadiscordmultiverse', 'DiscordManagedServer')
    Group = apps.get_model('auth', 'Group')
    for d in DiscordManagedServer.objects.all():
        excl = d.ignored_groups.all()
        incl = Group.objects.all().exclude(id__in=excl.values_list("id"))
        for g in incl:
            d.included_groups.add(g)


def sync_groups_back(apps, schema_editor):
    pass  # do nothing going back is useless, but dont fail...


class Migration(migrations.Migration):

    dependencies = [
        ('aadiscordmultiverse', '0005_discordmanagedserver_include_all_managed_groups_and_more'),
    ]

    operations = [
        migrations.RunPython(sync_groups_fwd, sync_groups_back)
    ]
