# Generated by Django 4.2.13 on 2024-08-20 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aadiscordmultiverse', '0006_sync_groups_to_new_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discordmanagedserver',
            name='ignored_groups',
        ),
    ]
